Updated to scout-actions@v3.1

diff --git a/.github/workflows/scout.yml b/.github/workflows/scout.yml
--- a/.github/workflows/scout.yml
+++ b/.github/workflows/scout.yml
@@ -16,10 +16,15 @@ jobs:
         uses: actions/checkout@v4
 
       - name: do scout
-        uses: coinfabrik/scout-actions@v3
-        with:
-          target: ''
+        uses: coinfabrik/scout-actions@v3.1
 
       - uses: mshick/add-pr-comment@v2.8.2
         with:
           message-path:  ${{ github.workspace }}/report.md
+
+      - name: Check for error
+        run: |
+          if [ -f "${{ github.workspace }}/FAIL" ]; then
+            echo "Error: Scout found issues."
+            exit 1
+          fi
